openapi: 3.0.1
info:
  title: MediatorAPI
  description: API Definition of MediatorAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/mediatorapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
