openapi: 3.0.1
info:
  title: GreeterAPI
  description: API Definition of GreeterAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/greeterapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
