openapi: 3.0.1
info:
  title: StockQuoteProxy
  description: API Definition of StockQuoteProxy
  version: 1.0.0
servers:
- url: http://localhost:8290/stockquoteproxy
paths:
  /:
    get:
      responses:
        default:
          description: Default response
